version: '3.4'

services:
  salesapi:
    image: salesapi
    build: 
      context: SalesApi/
      dockerfile: Dockerfile
  salesui:
    image: salesui
    build: 
      context: SalesUI/
      dockerfile: Dockerfile
    depends_on:
      - salesapi