version: '3.4'

services:
  salesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7174
      - ConnectionStrings__DefaultConnection=${ProdConnectionStrings}
      - SqlProvider=SqlServer
    ports:
      - 7174:7174
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  salesui:  
    ports:
      - 80:80