version: '3.4'

services:
  salesdb:
    image: postgres
    restart: always
  salesapi:
    image: salesapi
    build: 
      context: SalesApi/SalesApi/
      dockerfile: Dockerfile
    depends_on:
      - salesdb
  salesui:
    image: salesui
    build: 
      context: SalesUI/
      dockerfile: Dockerfile
    depends_on:
      - salesapi